# autogenerated by txs
#include:etoolbox
#include:keyval
\LogreqDTDVersion#S
\comment#S
\do#S
\do{arg1}#S
\expandafter#S
\protect#S
\DeclareLogreqAttribute#S
\DeclareLogreqContainer#S
\DeclareLogreqElement#S
\\logrequest#S
\logrequest#S
\ltxrequest#S
etoolbox.sty#S
