# autogenerated by txs
\binom#S
\currentmathstyle#S
\dbinom#S
\dfrac#S
\displaystyle#S
\fracstyle#S
\genfrac{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#S
\mathchoice#S
\mathsub#S
\mathsup#S
\sb{arg1}#S
\scriptscriptstyle#S
\scriptstyle#S
\sp{arg1}#S
\subsupstyle#S
\tbinom#S
\textstyle#S
\tfrac#S
\directlua#S
\displaystyle #S
\genfrac #S
\mathstyle#S
\scriptscriptstyle #S
\scriptstyle #S
\textstyle #S
