# autogenerated by txs
\Big#S
\Bigg#S
\amalg#S
\big#S
\bigg#S
\boldmath#S
\coprod#S
\hbar#S
\omicron#Sm
\rmdefault#S
\OML/ptmcm/m/it#S
\OMS/pzccm/m/n#S
\OMX/psycm/m/n#S
\OT1/ptm/bx/n#S
\OT1/ptm/m/it#S
\OT1/ptmcm/m/n#S
\omicron #S
\symbold#S
\symitalic#S
