# autogenerated by txs
\deleteduplicates{arg1}{arg2}#S
\expandafter#S
\intersectsets{arg1}{arg2}#S
\iselementofset{arg1}{arg2}#S
\iterate#S
\listset{arg1}#S
\lookup#S
\minussets{arg1}#S
\newsetsimple{arg1}{arg2}#S
\newset{arg1}{arg2}#S
\setseparator#S
\sizeofset{arg1}#S
\sortset{arg1}{arg2}#S
\temp#S
\unionsets{arg1}{arg2}#S
\newset#S
