# autogenerated by txs
\UCSPU#S
\UCSPUrange{arg1}{arg2}#S
\UCSPU{arg1}#S
\fontencoding#S
\foreignlanguage#S
\pdfstringdefPreHook#S
\pdfstringdef{arg1}{arg2}#S
\selectfont#S
\selectlanguage#S
\ucspu#S
\unichar#S
\unichar{arg1}#S
