# autogenerated by txs
#include:pgfkeys
#include:pgfopts
#include:xcolor
\begin{ytableau}#S
\end{ytableau}#S
\expandafter#S
\none#S
\ydiagram{arg1}{arg2}#S
\ytableausetup{arg1}#S
\ytableaushort{arg1}{arg2}#S
\\ydiagram#S
\\ytableau#S
\\ytableaushort#S
